MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - '10.12'                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '10.14'                # [osx and x86_64]
  

c_compiler:
  - vs2019
cxx_compiler:
  - vs2019