package:
    name: qt6molecularnetwork
    version: {{ GIT_DESCRIBE_TAG | replace("v", "") }}

source:
    path: ../

build:
    number: 0
    ignore_run_exports:
        # Only for rdkit
        - python_abi

requirements:
    build:
        - cmake
        - {{ compiler('cxx') }}
        - make                           # [not win]
        - ninja                          # [win]
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}        # [linux]
        - {{ cdt('libxdamage') }}        # [linux]
        - {{ cdt('libxxf86vm') }}        # [linux]
        - {{ cdt('libxext') }}           # [linux]
    host:
        - cairo
        - freetype
        - boost-cpp
        - eigen
        - qt6-main
        - python
        - {{ pin_compatible('rdkit', max_pin='x.x') }}
        - {{ pin_compatible('rdkit-dev', max_pin='x.x') }}  # [win]
    run:
        - {{ pin_compatible('rdkit', max_pin='x.x') }}
    
test:
    commands:
        - if not exist %LIBRARY_BIN%\\qt6molecularnetwork.dll exit 1                                      # [win]
        - if not exist %LIBRARY_INC%\\qt6molecularnetwork\\node.h exit 1                                  # [win]
        - if not exist %LIBRARY_LIB%\\cmake\\qt6molecularnetwork\\qt6molecularnetworkConfig.cmake exit 1  # [win]
        - test -f $PREFIX/lib/libqt6molecularnetwork${SHLIB_EXT}                                          # [unix]
        - test -f $PREFIX/include/qt6molecularnetwork/node.h                                              # [unix]
        - test -f $PREFIX/lib/cmake/qt6molecularnetwork/qt6molecularnetworkConfig.cmake                   # [unix]

outputs:
  - name: qt6molecularnetwork
  - name: pyside6mn
    build:
      script: python -m pip install --global-option="-DPython3_EXECUTABLE:FILEPATH={python}" . -vv
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - clangdev
        - cmake
        - make                                # [not win]
        - libcxx                              # [linux]
        - {{ cdt('mesa-libgl-devel') }}       # [linux]
        - {{ cdt('mesa-dri-drivers') }}       # [linux]
        - {{ cdt('libselinux') }}             # [linux]
        - {{ cdt('libxdamage') }}             # [linux]
        - {{ cdt('libxxf86vm') }}             # [linux]
        - {{ cdt('libxext') }}                # [linux]
      host:
        - {{ pin_subpackage('qt6molecularnetwork', exact=True) }}
        - {{ pin_compatible('rdkit-dev', max_pin='x.x') }}  # [win]
        - {{ pin_compatible('rdkit', max_pin='x.x') }}
        - python
        - pyside6
        - qt6-main
        - versioneer
        - cmake-build-extension
        - eigen
        - pip
        - setuptools
        - libclang
        - cairo
        - freetype
      run:
        - python
        - {{ pin_subpackage('qt6molecularnetwork', exact=True) }}
        - {{ pin_compatible('rdkit', max_pin='x.x') }}
        - pywin32                             # [win]
        - pyside6
        - tinycss2
    test:
      imports:
        - PySide6MolecularNetwork
        - PySide6MolecularNetwork.qmn

about:
    home: https://github.com/metgem/QtMolecularNetwork
    license: GPL-3.0
    license_family: GPL
    license_file: 'LICENSE'
    summary: 'Widgets used for visualisation of graph in MetGem'
    description: 'Widgets used for visualisation of graph in `MetGem`'
    doc_url: ''
    dev_url: 'https://github.com/metgem/QtMolecularNetwork'

extra:
    recipe-maintainers:
      - n-elie
