{% set version = "0.6.2" %}
{% set rdkit_version = "2022.03" %}

package:
    name: qt6molecularnetwork
    version: {{ version }}

source:
    path: ../

build:
    number: 0

requirements:
    build:
        - cmake
        - {{ compiler('cxx') }}
        - make                                # [not win]
        - eigen
        - {{ cdt('mesa-libgl-devel') }}       # [linux]
        - {{ cdt('mesa-dri-drivers') }}       # [linux]
        - {{ cdt('libselinux') }}             # [linux]
        - {{ cdt('libxdamage') }}             # [linux]
        - {{ cdt('libxxf86vm') }}             # [linux]
        - {{ cdt('libxext') }}                # [linux]
    host:
        - python {{ python }}
        - cairo
        - freetype
        - qt6-main
        - rdkit-dev ={{ rdkit_version }}
    run:
        - rdkit ={{ rdkit_version }}
    
test:
    commands:
        - if not exist %LIBRARY_BIN%\\qt6molecularnetwork.dll exit 1                                      # [win]
        - if not exist %LIBRARY_INC%\\qt6molecularnetwork\\node.h exit 1                                  # [win]
        - if not exist %LIBRARY_LIB%\\cmake\\qt6molecularnetwork\\qt6molecularnetworkConfig.cmake exit 1  # [win]
        - test -f $PREFIX/lib/libqt6molecularnetwork${SHLIB_EXT}                                          # [unix]
        - test -f $PREFIX/include/qt6molecularnetwork/node.h                                              # [unix]
        - test -f $PREFIX/lib/cmake/qt6molecularnetwork/qt6molecularnetworkConfig.cmake                   # [unix]

outputs:
  - name: qt6molecularnetwork
  - name: pyside2mn
    build:
      script: python -m pip install . -vv
    version: {{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - clangdev
        - cmake
        - make                                # [not win]
        - libcxx                              # [linux]
        - {{ cdt('mesa-libgl-devel') }}       # [linux]
        - {{ cdt('mesa-dri-drivers') }}       # [linux]
        - {{ cdt('libselinux') }}             # [linux]
        - {{ cdt('libxdamage') }}             # [linux]
        - {{ cdt('libxxf86vm') }}             # [linux]
        - {{ cdt('libxext') }}                # [linux]
      host:
        - {{ pin_subpackage('qt6molecularnetwork', exact=True) }}
        - python {{ python }}
        - rdkit-dev ={{ rdkit_version }}
        - pyside6
        - qt6-main
        - cmake-build-extension
        - eigen
        - pip
        - setuptools
        - libclang
        - cairo
        - freetype
      run:
        - python {{ python }}
        - {{ pin_subpackage('qt6molecularnetwork', exact=True) }}
        - pywin32                             # [win]
        - pyside6
        - rdkit ={{ rdkit_version }}
        - tinycss2
    test:
      imports:
        - PySide2MolecularNetwork
        - PySide2MolecularNetwork.qmn

about:
    home: https://github.com/metgem/QtMolecularNetwork
    license: GPL-3.0
    license_family: GPL
    license_file: 'LICENSE'
    summary: 'Widgets used for visualisation of graph in MetGem'
    description: 'Widgets used for visualisation of graph in `MetGem`'
    doc_url: ''
    dev_url: 'https://github.com/metgem/QtMolecularNetwork'

extra:
    recipe-maintainers:
      - n-elie
