name: Tests

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda packages
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}
    - name: Set up Python ${{ matrix.python-version }} (Miniconda)
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: tests
        use-only-tar-bz2: true
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
    - name: Install build dependencies
      shell: bash -l {0}
      run: |
        conda install -n base conda-build conda-verify pyside2
        conda install anaconda-client
    - name: Install libiconv
      shell: bash -l {0}
      run: conda install -n base libiconv
      if: runner.os == 'Linux'
    - name: Build
      shell: bash -l {0}
      run: |
        conda build recipe --python ${{ matrix.python-version }}
        conda install qtmolecularnetwork pyside2mn -c local
    - name: Install test dependencies
      shell: bash -l {0}
      run: conda install -q tinycss2 pytest pylint pytest-pylint toml pytest-qt pytest-cov codecov pytest-mock
    - name: Install xvfb
      shell: bash -l {0}
      run: conda install pytest-xvfb
      if: runner.os == 'Linux'
    - name: Test with pytest
      shell: bash -l {0}
      run: cd tests && pytest --cov=PySide2MolecularNetwork --cov-report=xml .
    - name: Upload coverage
      if: success()
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        name: ${{ runner.os }} Python ${{ matrix.python-version }}
